// Category definitions for the homepage grid and category detail pages.
// slugs: all skills assigned to this category (shown in grid + category page)
// featuredSlugs: enterprise-managed skills shown with "Featured" label at top
//   (leave empty until Anthropic API enterprise skill sync is built)
// Ops team: edit slugs/featuredSlugs to curate the hub's categories.
export const CATEGORIES = [
  {
    id: 'writing-comms',
    label: 'Writing & Comms',
    borderColor: '#c4b5fd',
    textColor: '#7c3aed',
    featuredSlugs: [],
    slugs: [
      'nava-labs-style',
      'ux-writing',
      'update-docs',
      'caseworker-communication',
    ],
  },
  {
    id: 'research-analysis',
    label: 'Research & Analysis',
    borderColor: '#94a3b8',
    textColor: '#475569',
    featuredSlugs: [],
    slugs: [
      'diagram',
      'analyze-codebase',
      'design-review',
      'index-inputs',
      'review-stats',
      'dso-test-quality-report',
    ],
  },
  {
    id: 'planning',
    label: 'Planning',
    borderColor: '#6ee7b7',
    textColor: '#059669',
    featuredSlugs: [],
    slugs: [
      'brainstorm',
      'implementation-plan',
      'prioritize-epics',
      'preplanning',
      'roadmap',
      'interface-contracts',
      'sprint',
      'plan-review',
      'oscillation-check',
      'audit-plans',
      'open-items',
    ],
  },
  {
    id: 'dev-code',
    label: 'Dev & Code',
    borderColor: '#fcd34d',
    textColor: '#92400e',
    featuredSlugs: [],
    slugs: [
      'fix-bug',
      'debug-everything',
      'playwright-debug',
      'e2e-test',
      'test',
      'typecheck',
      'lint',
      'build',
      'review',
      'resolve-conflicts',
      'respond-to-pr-comments',
      'pre-push-check',
      'verification-before-completion',
      'validate-work',
      'frontend-design',
      'tweakcn-design',
      'color-and-contrast',
      'responsive-design',
      'spatial-design',
      'typography',
      'interaction-design',
      'motion-design',
      'skill-refactor',
    ],
  },
  {
    id: 'ops-automation',
    label: 'Ops & Automation',
    borderColor: '#d1d5db',
    textColor: '#374151',
    featuredSlugs: [],
    slugs: [
      'retro',
      'tickets-health',
      'generate-ui',
      'flow-screenshots',
      'create-bug',
      'agent-browser',
      'retro-finalize',
      'add-learning',
      'end-session',
      'session-start',
    ],
  },
];

export const SUBMIT_FORM_URL =
  'https://docs.google.com/forms/d/e/1FAIpQLSdW3RSdwVvbFDFz_OBdZ1CzyNq_pYq_z8zsR0NdOknRApcR6A/viewform?usp=preview';
